import { LeagueSettings } from '../types';

export const DEFAULT_LEAGUE_SETTINGS: LeagueSettings = {
  skillLevel: 'All-American',
  coachXP: 'Normal',
  injuryEnabled: true,
  manualProgressionXP: 100,
  playcallCooldownEnabled: false,
  playcallCooldownValue: 5,
  quarterLength: 6,
  acceleratedClockEnabled: true,
  minPlayclockTime: 15,
  wearAndTearEnabled: true,
  wearAndTearSettings: {
    normalTackleImpact: 50,
    catchTackleImpact: 50,
    hitStickImpact: 50,
    cutStickImpact: 50,
    defenderTackleAdvantageImpact: 50,
    sackImpact: 50,
    impactBlockImpact: 50,
    perPlayRecovery: 50,
    perTimeoutRecovery: 50,
    betweenQuarterRecovery: 50,
    halftimeRecovery: 50,
    weekToWeekRecovery: 50,
    inGameHealingReservePool: 50,
  },
  maxTransfersPerTeam: 15,
  userPlayerTransferChance: 55,
  cpuPlayerTransferChance: 55,
  maxUsers: 32,
  crossPlayEnabled: true,
  houseRules: '',
};
