export interface School {
  name: string;
  abbreviation: string;
  logoId?: string | number;
  conference: string;
  color: string;
  secondaryColor?: string;
  isFCS?: boolean;
}

export const SCHOOLS: School[] = [
  { name: "Air Force", abbreviation: "AFA", logoId: 2005, conference: "Mountain West", color: "#003087" },
  { name: "Akron", abbreviation: "AKR", logoId: 2006, conference: "MAC", color: "#041E42" },
  { name: "Alabama", abbreviation: "BAMA", logoId: 333, conference: "SEC", color: "#9E1B32" },
  { name: "Appalachian State", abbreviation: "APP", logoId: 2026, conference: "Sun Belt", color: "#222222" },
  { name: "Arizona", abbreviation: "ARIZ", logoId: 12, conference: "Big 12", color: "#CC0033" },
  { name: "Arizona State", abbreviation: "ASU", logoId: 9, conference: "Big 12", color: "#8C1D40" },
  { name: "Arkansas", abbreviation: "ARK", logoId: 8, conference: "SEC", color: "#9D2235" },
  { name: "Arkansas State", abbreviation: "ARST", logoId: 2032, conference: "Sun Belt", color: "#CC092F" },
  { name: "Army", abbreviation: "ARMY", logoId: 349, conference: "AAC", color: "#2C2A29" },
  { name: "Auburn", abbreviation: "AUB", logoId: 2, conference: "SEC", color: "#0C2340" },
  { name: "Ball State", abbreviation: "BALL", logoId: 2050, conference: "MAC", color: "#BA0C2F" },
  { name: "Baylor", abbreviation: "BAY", logoId: 239, conference: "Big 12", color: "#154734" },
  { name: "Boise State", abbreviation: "BSU", logoId: 68, conference: "Mountain West", color: "#0033A0" },
  { name: "Boston College", abbreviation: "BC", logoId: 103, conference: "ACC", color: "#800000" },
  { name: "Bowling Green", abbreviation: "BGSU", logoId: 25, conference: "MAC", color: "#FE5000" },
  { name: "Buffalo", abbreviation: "BUF", logoId: 2084, conference: "MAC", color: "#005BBB" },
  { name: "BYU", abbreviation: "BYU", logoId: 252, conference: "Big 12", color: "#002E5D" },
  { name: "California", abbreviation: "CAL", logoId: 25, conference: "ACC", color: "#003262" },
  { name: "Central Michigan", abbreviation: "CMU", logoId: 2117, conference: "MAC", color: "#6A0032" },
  { name: "Charlotte", abbreviation: "CLT", logoId: 2429, conference: "AAC", color: "#005035" },
  { name: "Cincinnati", abbreviation: "CIN", logoId: 2132, conference: "Big 12", color: "#E00122" },
  { name: "Clemson", abbreviation: "CLEM", logoId: 228, conference: "ACC", color: "#F56600" },
  { name: "Coastal Carolina", abbreviation: "CCU", logoId: 324, conference: "Sun Belt", color: "#006969" },
  { name: "Colorado", abbreviation: "COLO", logoId: 38, conference: "Big 12", color: "#CFB87C" },
  { name: "Colorado State", abbreviation: "CSU", logoId: 36, conference: "Mountain West", color: "#1E4D2B" },
  { name: "Delaware", abbreviation: "DEL", logoId: 48, conference: "C-USA", color: "#00539B" },
  { name: "Duke", abbreviation: "DUKE", logoId: 150, conference: "ACC", color: "#003087" },
  { name: "East Carolina", abbreviation: "ECU", logoId: 151, conference: "AAC", color: "#592A8A" },
  { name: "Eastern Michigan", abbreviation: "EMU", logoId: 2199, conference: "MAC", color: "#006633" },
  { name: "FCS East", abbreviation: "FCSE", logoId: "/assets/logos/resize.webp", conference: "FCS", color: "#444444", isFCS: true },
  { name: "FCS West", abbreviation: "FCSW", logoId: "/assets/logos/resize.webp", conference: "FCS", color: "#444444", isFCS: true },
  { name: "FCS Midwest", abbreviation: "FCSM", logoId: "/assets/logos/resize.webp", conference: "FCS", color: "#444444", isFCS: true },
  { name: "FCS Southeast", abbreviation: "FCSSE", logoId: "/assets/logos/resize.webp", conference: "FCS", color: "#444444", isFCS: true },
  { name: "FCS Northwest", abbreviation: "FCSNW", logoId: "/assets/logos/resize.webp", conference: "FCS", color: "#444444", isFCS: true },
  { name: "Florida", abbreviation: "FLA", logoId: 57, conference: "SEC", color: "#0021A5" },
  { name: "Florida Atlantic", abbreviation: "FAU", logoId: 2226, conference: "AAC", color: "#003366" },
  { name: "Florida International", abbreviation: "FIU", logoId: 2229, conference: "C-USA", color: "#081E3F" },
  { name: "Florida State", abbreviation: "FSU", logoId: 52, conference: "ACC", color: "#782F40" },
  { name: "Fresno State", abbreviation: "FRES", logoId: 278, conference: "Mountain West", color: "#C41230" },
  { name: "Georgia", abbreviation: "UGA", logoId: 61, conference: "SEC", color: "#BA0C2F" },
  { name: "Georgia Southern", abbreviation: "GASO", logoId: 290, conference: "Sun Belt", color: "#011E41" },
  { name: "Georgia State", abbreviation: "GAST", logoId: 2247, conference: "Sun Belt", color: "#0039A6" },
  { name: "Georgia Tech", abbreviation: "GT", logoId: 59, conference: "ACC", color: "#B3A369" },
  { name: "Hawaii", abbreviation: "HAW", logoId: 62, conference: "Mountain West", color: "#024731" },
  { name: "Houston", abbreviation: "HOU", logoId: 248, conference: "Big 12", color: "#C8102E" },
  { name: "Illinois", abbreviation: "ILL", logoId: 356, conference: "Big Ten", color: "#E84A27" },
  { name: "Indiana", abbreviation: "IND", logoId: 84, conference: "Big Ten", color: "#990000" },
  { name: "Iowa", abbreviation: "IOWA", logoId: 2294, conference: "Big Ten", color: "#FFCD00" },
  { name: "Iowa State", abbreviation: "ISU", logoId: 66, conference: "Big 12", color: "#C8102E" },
  { name: "Jacksonville State", abbreviation: "JSU", logoId: 2310, conference: "C-USA", color: "#CC0000" },
  { name: "James Madison", abbreviation: "JMU", logoId: 256, conference: "Sun Belt", color: "#450084" },
  { name: "Kansas", abbreviation: "KU", logoId: 2305, conference: "Big 12", color: "#0051BA" },
  { name: "Kansas State", abbreviation: "KSU", logoId: 2306, conference: "Big 12", color: "#512888" },
  { name: "Kennesaw State", abbreviation: "KENN", logoId: 2316, conference: "C-USA", color: "#FFC629" },
  { name: "Kent State", abbreviation: "KENT", logoId: 2309, conference: "MAC", color: "#002664" },
  { name: "Kentucky", abbreviation: "UK", logoId: 96, conference: "SEC", color: "#0033A0" },
  { name: "Liberty", abbreviation: "LIB", logoId: 2335, conference: "C-USA", color: "#002D62" },
  { name: "LSU", abbreviation: "LSU", logoId: 99, conference: "SEC", color: "#461D7C" },
  { name: "Louisiana", abbreviation: "ULL", logoId: 309, conference: "Sun Belt", color: "#CE181E" },
  { name: "Louisiana Tech", abbreviation: "LT", logoId: 2348, conference: "C-USA", color: "#002F8B" },
  { name: "Louisville", abbreviation: "LOU", logoId: 97, conference: "ACC", color: "#AD0000" },
  { name: "Marshall", abbreviation: "HERD", logoId: 276, conference: "Sun Belt", color: "#00B140" },
  { name: "Maryland", abbreviation: "MD", logoId: 120, conference: "Big Ten", color: "#E03A3E" },
  { name: "Memphis", abbreviation: "MEM", logoId: 235, conference: "AAC", color: "#003087" },
  { name: "Miami (FL)", abbreviation: "MIA", logoId: 2390, conference: "ACC", color: "#F47321" },
  { name: "Miami (OH)", abbreviation: "MOH", logoId: 193, conference: "MAC", color: "#B61E2E" },
  { name: "Michigan", abbreviation: "MICH", logoId: 130, conference: "Big Ten", color: "#00274C" },
  { name: "Michigan State", abbreviation: "MSU", logoId: 127, conference: "Big Ten", color: "#18453B" },
  { name: "Middle Tennessee", abbreviation: "MTSU", logoId: 2393, conference: "C-USA", color: "#0066CC" },
  { name: "Minnesota", abbreviation: "MINN", logoId: 135, conference: "Big Ten", color: "#7A0019" },
  { name: "Mississippi State", abbreviation: "MSST", logoId: 344, conference: "SEC", color: "#660000" },
  { name: "Missouri", abbreviation: "MIZZ", logoId: 142, conference: "SEC", color: "#F1B82D" },
  { name: "Missouri State", abbreviation: "MOST", logoId: 262, conference: "C-USA", color: "#5E0009" },
  { name: "Navy", abbreviation: "NAVY", logoId: 2426, conference: "AAC", color: "#00205B" },
  { name: "NC State", abbreviation: "NCST", logoId: 152, conference: "ACC", color: "#CC0000" },
  { name: "Nebraska", abbreviation: "NEB", logoId: 158, conference: "Big Ten", color: "#E41C38" },
  { name: "Nevada", abbreviation: "NEV", logoId: 2440, conference: "Mountain West", color: "#003366" },
  { name: "New Mexico", abbreviation: "UNM", logoId: 167, conference: "Mountain West", color: "#BA0C2F" },
  { name: "New Mexico State", abbreviation: "NMSU", logoId: 166, conference: "C-USA", color: "#891216" },
  { name: "North Carolina", abbreviation: "UNC", logoId: 153, conference: "ACC", color: "#7BAFD4" },
  { name: "North Texas", abbreviation: "UNT", logoId: 249, conference: "AAC", color: "#00853E" },
  { name: "Northern Illinois", abbreviation: "NIU", logoId: 2459, conference: "MAC", color: "#BA0C2F" },
  { name: "Northwestern", abbreviation: "NU", logoId: 77, conference: "Big Ten", color: "#4E2A84" },
  { name: "Notre Dame", abbreviation: "ND", logoId: 87, conference: "Independent", color: "#0C2340" },
  { name: "Ohio", abbreviation: "OHIO", logoId: 195, conference: "MAC", color: "#00694E" },
  { name: "Ohio State", abbreviation: "OSU", logoId: 194, conference: "Big Ten", color: "#BB0000" },
  { name: "Oklahoma", abbreviation: "OU", logoId: 201, conference: "SEC", color: "#841617" },
  { name: "Oklahoma State", abbreviation: "OKST", logoId: 197, conference: "Big 12", color: "#FF6500" },
  { name: "Old Dominion", abbreviation: "ODU", logoId: 295, conference: "Sun Belt", color: "#003057" },
  { name: "Ole Miss", abbreviation: "MISS", logoId: 145, conference: "SEC", color: "#CE1126" },
  { name: "Oregon", abbreviation: "ORE", logoId: 2483, conference: "Big Ten", color: "#154734" },
  { name: "Oregon State", abbreviation: "ORST", logoId: 204, conference: "Pac-12", color: "#DC4405" },
  { name: "Penn State", abbreviation: "PSU", logoId: 213, conference: "Big Ten", color: "#041E42" },
  { name: "Pittsburgh", abbreviation: "PITT", logoId: 221, conference: "ACC", color: "#003594" },
  { name: "Purdue", abbreviation: "PUR", logoId: 2509, conference: "Big Ten", color: "#CEB888" },
  { name: "Rice", abbreviation: "RICE", logoId: 242, conference: "AAC", color: "#00205B" },
  { name: "Rutgers", abbreviation: "RUTG", logoId: 164, conference: "Big Ten", color: "#CC0033" },
  { name: "Sam Houston", abbreviation: "SHSU", logoId: 2534, conference: "C-USA", color: "#F05A28" },
  { name: "San Diego State", abbreviation: "SDSU", logoId: 21, conference: "Mountain West", color: "#A6192E" },
  { name: "San Jose State", abbreviation: "SJSU", logoId: 23, conference: "Mountain West", color: "#0055A2" },
  { name: "SMU", abbreviation: "SMU", logoId: 2567, conference: "ACC", color: "#354CA1" },
  { name: "South Alabama", abbreviation: "USA", logoId: 6, conference: "Sun Belt", color: "#00205B" },
  { name: "South Carolina", abbreviation: "SC", logoId: 2579, conference: "SEC", color: "#73000A" },
  { name: "South Florida", abbreviation: "USF", logoId: 58, conference: "AAC", color: "#006747" },
  { name: "Southern Miss", abbreviation: "USM", logoId: 2572, conference: "Sun Belt", color: "#FFAB00" },
  { name: "Stanford", abbreviation: "STAN", logoId: 24, conference: "ACC", color: "#8C1515" },
  { name: "Syracuse", abbreviation: "SYR", logoId: 183, conference: "ACC", color: "#F76900" },
  { name: "TCU", abbreviation: "TCU", logoId: 2628, conference: "Big 12", color: "#4D1979" },
  { name: "Temple", abbreviation: "TEMP", logoId: 218, conference: "AAC", color: "#9D2235" },
  { name: "Tennessee", abbreviation: "TENN", logoId: 2633, conference: "SEC", color: "#FF8200" },
  { name: "Texas", abbreviation: "TEX", logoId: 251, conference: "SEC", color: "#BF5700" },
  { name: "Texas A&M", abbreviation: "TAMU", logoId: 245, conference: "SEC", color: "#500000" },
  { name: "Texas State", abbreviation: "TXST", logoId: 326, conference: "Sun Belt", color: "#501214" },
  { name: "Texas Tech", abbreviation: "TTU", logoId: 2641, conference: "Big 12", color: "#CC0000" },
  { name: "Toledo", abbreviation: "TOL", logoId: 2649, conference: "MAC", color: "#15397F" },
  { name: "Troy", abbreviation: "TROY", logoId: 2653, conference: "Sun Belt", color: "#8A2432" },
  { name: "Tulane", abbreviation: "TULN", logoId: 2655, conference: "AAC", color: "#006747" },
  { name: "Tulsa", abbreviation: "TUL", logoId: 202, conference: "AAC", color: "#002D62" },
  { name: "UAB", abbreviation: "UAB", logoId: 5, conference: "AAC", color: "#006341" },
  { name: "UCF", abbreviation: "UCF", logoId: 2116, conference: "Big 12", color: "#BA9B37" },
  { name: "UCLA", abbreviation: "UCLA", logoId: 26, conference: "Big Ten", color: "#2D68C4" },
  { name: "UConn", abbreviation: "CONN", logoId: 41, conference: "Independent", color: "#000E2F" },
  { name: "UL Monroe", abbreviation: "ULM", logoId: 2433, conference: "Sun Belt", color: "#840029" },
  { name: "UMass", abbreviation: "UMAS", logoId: 113, conference: "Independent", color: "#881224" },
  { name: "UNLV", abbreviation: "UNLV", logoId: 2439, conference: "Mountain West", color: "#CF0A2C" },
  { name: "USC", abbreviation: "USC", logoId: 30, conference: "Big Ten", color: "#990000" },
  { name: "UTEP", abbreviation: "UTEP", logoId: 2638, conference: "C-USA", color: "#041E42" },
  { name: "UTSA", abbreviation: "UTSA", logoId: 2636, conference: "AAC", color: "#0C2340" },
  { name: "Utah", abbreviation: "UTAH", logoId: 254, conference: "Big 12", color: "#CC0000" },
  { name: "Utah State", abbreviation: "USU", logoId: 328, conference: "Mountain West", color: "#00263A" },
  { name: "Vanderbilt", abbreviation: "VANDY", logoId: 238, conference: "SEC", color: "#000000" },
  { name: "Virginia", abbreviation: "UVA", logoId: 258, conference: "ACC", color: "#232D4B" },
  { name: "Virginia Tech", abbreviation: "VT", logoId: 259, conference: "ACC", color: "#630031" },
  { name: "Wake Forest", abbreviation: "WAKE", logoId: 154, conference: "ACC", color: "#9E7E38" },
  { name: "Washington", abbreviation: "WASH", logoId: 264, conference: "Big Ten", color: "#4B2E83" },
  { name: "Washington State", abbreviation: "WSU", logoId: 265, conference: "Pac-12", color: "#981E32" },
  { name: "West Virginia", abbreviation: "WVU", logoId: 277, conference: "Big 12", color: "#002855" },
  { name: "Western Kentucky", abbreviation: "WKU", logoId: 98, conference: "C-USA", color: "#E31837" },
  { name: "Western Michigan", abbreviation: "WMU", logoId: 2711, conference: "MAC", color: "#6C4023" },
  { name: "Wisconsin", abbreviation: "WISC", logoId: 275, conference: "Big Ten", color: "#C5050C" },
  { name: "Wyoming", abbreviation: "WYO", logoId: 2751, conference: "Mountain West", color: "#492F24" }
].sort((a, b) => a.name.localeCompare(b.name));
