export interface School {
  name: string;
  logoId?: string | number;
  conference: string;
  color: string;
}

export const SCHOOLS: School[] = [
  { name: "Air Force", logoId: 2005, conference: "Mountain West", color: "#003087" },
  { name: "Akron", logoId: 2006, conference: "MAC", color: "#041E42" },
  { name: "Alabama", logoId: 333, conference: "SEC", color: "#9E1B32" },
  { name: "Appalachian State", logoId: 2026, conference: "Sun Belt", color: "#222222" },
  { name: "Arizona", logoId: 12, conference: "Big 12", color: "#CC0033" },
  { name: "Arizona State", logoId: 9, conference: "Big 12", color: "#8C1D40" },
  { name: "Arkansas", logoId: 8, conference: "SEC", color: "#9D2235" },
  { name: "Arkansas State", logoId: 2032, conference: "Sun Belt", color: "#CC092F" },
  { name: "Army", logoId: 349, conference: "AAC", color: "#2C2A29" },
  { name: "Auburn", logoId: 2, conference: "SEC", color: "#0C2340" },
  { name: "Ball State", logoId: 2050, conference: "MAC", color: "#BA0C2F" },
  { name: "Baylor", logoId: 239, conference: "Big 12", color: "#154734" },
  { name: "Boise State", logoId: 68, conference: "Mountain West", color: "#0033A0" },
  { name: "Boston College", logoId: 103, conference: "ACC", color: "#800000" },
  { name: "Bowling Green", logoId: 189, conference: "MAC", color: "#FE5000" },
  { name: "Buffalo", logoId: 2084, conference: "MAC", color: "#005BBB" },
  { name: "BYU", logoId: 252, conference: "Big 12", color: "#002E5D" },
  { name: "California", logoId: 25, conference: "ACC", color: "#003262" },
  { name: "Central Michigan", logoId: 2117, conference: "MAC", color: "#6A0032" },
  { name: "Charlotte", logoId: 2429, conference: "AAC", color: "#005035" },
  { name: "Cincinnati", logoId: 2132, conference: "Big 12", color: "#E00122" },
  { name: "Clemson", logoId: 228, conference: "ACC", color: "#F56600" },
  { name: "Coastal Carolina", logoId: 324, conference: "Sun Belt", color: "#006969" },
  { name: "Colorado", logoId: 38, conference: "Big 12", color: "#CFB87C" },
  { name: "Colorado State", logoId: 36, conference: "Mountain West", color: "#1E4D2B" },
  { name: "Duke", logoId: 150, conference: "ACC", color: "#003087" },
  { name: "East Carolina", logoId: 151, conference: "AAC", color: "#592A8A" },
  { name: "Eastern Michigan", logoId: 2199, conference: "MAC", color: "#006633" },
  { name: "Florida", logoId: 57, conference: "SEC", color: "#0021A5" },
  { name: "Florida Atlantic", logoId: 2226, conference: "AAC", color: "#003366" },
  { name: "Florida International", logoId: 2229, conference: "C-USA", color: "#081E3F" },
  { name: "Florida State", logoId: 52, conference: "ACC", color: "#782F40" },
  { name: "Fresno State", logoId: 278, conference: "Mountain West", color: "#C41230" },
  { name: "Georgia", logoId: 61, conference: "SEC", color: "#BA0C2F" },
  { name: "Georgia Southern", logoId: 290, conference: "Sun Belt", color: "#011E41" },
  { name: "Georgia State", logoId: 2247, conference: "Sun Belt", color: "#0039A6" },
  { name: "Georgia Tech", logoId: 59, conference: "ACC", color: "#B3A369" },
  { name: "Hawaii", logoId: 62, conference: "Mountain West", color: "#024731" },
  { name: "Houston", logoId: 248, conference: "Big 12", color: "#C8102E" },
  { name: "Illinois", logoId: 356, conference: "Big Ten", color: "#E84A27" },
  { name: "Indiana", logoId: 84, conference: "Big Ten", color: "#990000" },
  { name: "Iowa", logoId: 2294, conference: "Big Ten", color: "#FFCD00" },
  { name: "Iowa State", logoId: 66, conference: "Big 12", color: "#C8102E" },
  { name: "Jacksonville State", logoId: 2310, conference: "C-USA", color: "#CC0000" },
  { name: "James Madison", logoId: 256, conference: "Sun Belt", color: "#450084" },
  { name: "Kansas", logoId: 2305, conference: "Big 12", color: "#0051BA" },
  { name: "Kansas State", logoId: 2306, conference: "Big 12", color: "#512888" },
  { name: "Kennesaw State", logoId: 2316, conference: "C-USA", color: "#FFC629" },
  { name: "Kent State", logoId: 2309, conference: "MAC", color: "#002664" },
  { name: "Kentucky", logoId: 96, conference: "SEC", color: "#0033A0" },
  { name: "Liberty", logoId: 2335, conference: "C-USA", color: "#002D62" },
  { name: "LSU", logoId: 99, conference: "SEC", color: "#461D7C" },
  { name: "Louisiana", logoId: 309, conference: "Sun Belt", color: "#CE181E" },
  { name: "Louisiana Tech", logoId: 2348, conference: "C-USA", color: "#002F8B" },
  { name: "Louisville", logoId: 97, conference: "ACC", color: "#AD0000" },
  { name: "Marshall", logoId: 276, conference: "Sun Belt", color: "#00B140" },
  { name: "Maryland", logoId: 120, conference: "Big Ten", color: "#E03A3E" },
  { name: "Memphis", logoId: 235, conference: "AAC", color: "#003087" },
  { name: "Miami (FL)", logoId: 2390, conference: "ACC", color: "#F47321" },
  { name: "Miami (OH)", logoId: 193, conference: "MAC", color: "#B61E2E" },
  { name: "Michigan", logoId: 130, conference: "Big Ten", color: "#00274C" },
  { name: "Michigan State", logoId: 127, conference: "Big Ten", color: "#18453B" },
  { name: "Middle Tennessee", logoId: 2393, conference: "C-USA", color: "#0066CC" },
  { name: "Minnesota", logoId: 135, conference: "Big Ten", color: "#7A0019" },
  { name: "Mississippi State", logoId: 344, conference: "SEC", color: "#660000" },
  { name: "Missouri", logoId: 142, conference: "SEC", color: "#F1B82D" },
  { name: "Navy", logoId: 2426, conference: "AAC", color: "#00205B" },
  { name: "NC State", logoId: 152, conference: "ACC", color: "#CC0000" },
  { name: "Nebraska", logoId: 158, conference: "Big Ten", color: "#E41C38" },
  { name: "Nevada", logoId: 2440, conference: "Mountain West", color: "#003366" },
  { name: "New Mexico", logoId: 167, conference: "Mountain West", color: "#BA0C2F" },
  { name: "New Mexico State", logoId: 166, conference: "C-USA", color: "#891216" },
  { name: "North Carolina", logoId: 153, conference: "ACC", color: "#7BAFD4" },
  { name: "North Texas", logoId: 249, conference: "AAC", color: "#00853E" },
  { name: "Northern Illinois", logoId: 2459, conference: "MAC", color: "#BA0C2F" },
  { name: "Northwestern", logoId: 77, conference: "Big Ten", color: "#4E2A84" },
  { name: "Notre Dame", logoId: 87, conference: "Independent", color: "#0C2340" },
  { name: "Ohio", logoId: 195, conference: "MAC", color: "#00694E" },
  { name: "Ohio State", logoId: 194, conference: "Big Ten", color: "#BB0000" },
  { name: "Oklahoma", logoId: 201, conference: "SEC", color: "#841617" },
  { name: "Oklahoma State", logoId: 197, conference: "Big 12", color: "#FF6500" },
  { name: "Old Dominion", logoId: 295, conference: "Sun Belt", color: "#003057" },
  { name: "Ole Miss", logoId: 145, conference: "SEC", color: "#CE1126" },
  { name: "Oregon", logoId: 2483, conference: "Big Ten", color: "#154734" },
  { name: "Oregon State", logoId: 204, conference: "Pac-12", color: "#DC4405" },
  { name: "Penn State", logoId: 213, conference: "Big Ten", color: "#041E42" },
  { name: "Pittsburgh", logoId: 221, conference: "ACC", color: "#003594" },
  { name: "Purdue", logoId: 2509, conference: "Big Ten", color: "#CEB888" },
  { name: "Rice", logoId: 242, conference: "AAC", color: "#00205B" },
  { name: "Sam Houston", logoId: 2534, conference: "C-USA", color: "#F05A28" },
  { name: "San Diego State", logoId: 21, conference: "Mountain West", color: "#A6192E" },
  { name: "San Jose State", logoId: 23, conference: "Mountain West", color: "#0055A2" },
  { name: "SMU", logoId: 2567, conference: "ACC", color: "#354CA1" },
  { name: "South Alabama", logoId: 6, conference: "Sun Belt", color: "#00205B" },
  { name: "South Carolina", logoId: 2579, conference: "SEC", color: "#73000A" },
  { name: "South Florida", logoId: 58, conference: "AAC", color: "#006747" },
  { name: "Southern Miss", logoId: 2572, conference: "Sun Belt", color: "#FFAB00" },
  { name: "Stanford", logoId: 24, conference: "ACC", color: "#8C1515" },
  { name: "Syracuse", logoId: 183, conference: "ACC", color: "#F76900" },
  { name: "TCU", logoId: 2628, conference: "Big 12", color: "#4D1979" },
  { name: "Temple", logoId: 218, conference: "AAC", color: "#9D2235" },
  { name: "Tennessee", logoId: 2633, conference: "SEC", color: "#FF8200" },
  { name: "Texas", logoId: 251, conference: "SEC", color: "#BF5700" },
  { name: "Texas A&M", logoId: 245, conference: "SEC", color: "#500000" },
  { name: "Texas State", logoId: 326, conference: "Sun Belt", color: "#501214" },
  { name: "Texas Tech", logoId: 2641, conference: "Big 12", color: "#CC0000" },
  { name: "Toledo", logoId: 2649, conference: "MAC", color: "#15397F" },
  { name: "Troy", logoId: 2653, conference: "Sun Belt", color: "#8A2432" },
  { name: "Tulane", logoId: 2655, conference: "AAC", color: "#006747" },
  { name: "Tulsa", logoId: 202, conference: "AAC", color: "#002D62" },
  { name: "UAB", logoId: 5, conference: "AAC", color: "#006341" },
  { name: "UCF", logoId: 2116, conference: "Big 12", color: "#BA9B37" },
  { name: "UCLA", logoId: 26, conference: "Big Ten", color: "#2D68C4" },
  { name: "UConn", logoId: 41, conference: "Independent", color: "#000E2F" },
  { name: "UMass", logoId: 113, conference: "Independent", color: "#881224" },
  { name: "UNLV", logoId: 2439, conference: "Mountain West", color: "#CF0A2C" },
  { name: "USC", logoId: 30, conference: "Big Ten", color: "#990000" },
  { name: "UTEP", logoId: 2638, conference: "C-USA", color: "#041E42" },
  { name: "UTSA", logoId: 2636, conference: "AAC", color: "#0C2340" },
  { name: "Utah", logoId: 254, conference: "Big 12", color: "#CC0000" },
  { name: "Utah State", logoId: 328, conference: "Mountain West", color: "#00263A" },
  { name: "Vanderbilt", logoId: 238, conference: "SEC", color: "#000000" },
  { name: "Virginia", logoId: 258, conference: "ACC", color: "#232D4B" },
  { name: "Virginia Tech", logoId: 259, conference: "ACC", color: "#630031" },
  { name: "Wake Forest", logoId: 154, conference: "ACC", color: "#9E7E38" },
  { name: "Washington", logoId: 264, conference: "Big Ten", color: "#4B2E83" },
  { name: "Washington State", logoId: 265, conference: "Pac-12", color: "#981E32" },
  { name: "West Virginia", logoId: 277, conference: "Big 12", color: "#002855" },
  { name: "Western Kentucky", logoId: 98, conference: "C-USA", color: "#E31837" },
  { name: "Western Michigan", logoId: 2711, conference: "MAC", color: "#6C4023" },
  { name: "Wisconsin", logoId: 275, conference: "Big Ten", color: "#C5050C" },
  { name: "Wyoming", logoId: 2751, conference: "Mountain West", color: "#492F24" }
].sort((a, b) => a.name.localeCompare(b.name));
